[[account]]
name = "my account name"
cookie = "my auth cookie"

# EXAMPLE:
# [[account]]
# name = "testaccount1"
# cookie = "auth=authcookie_; twoFactorAuth="
# proxy = "socks5://10.124.0.1:1080" # (OPTIONAL)
# You can add multiple accounts to the config.

[group]
name = "my group name"
id = "my group id"

# EXAMPLE:
# [group]
# name = "testgroup1"
# id = "grp_"
# You can only have one group.
